# Generated by Django 4.2.28 on 2026-02-28 09:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('year_published', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('book', 'Book'), ('dvd', 'DVD'), ('magazine', 'Magazine'), ('ebook', 'EBook'), ('audiobook', 'AudioBook')], max_length=20)),
                ('location', models.CharField(blank=True, default='General Section', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('is_digital', models.BooleanField(default=False)),
                ('file_format', models.CharField(blank=True, max_length=20)),
                ('file_size_mb', models.FloatField(default=0.0)),
                ('concurrent_access_limit', models.IntegerField(default=1)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('pages', models.IntegerField(default=0)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('runtime_minutes', models.IntegerField(default=0)),
                ('rating', models.CharField(blank=True, max_length=10)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('issue_number', models.CharField(blank=True, max_length=50)),
                ('issue_date', models.CharField(blank=True, max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('drm_protected', models.BooleanField(default=True)),
                ('narrator', models.CharField(blank=True, max_length=255)),
                ('duration_hours', models.FloatField(default=0.0)),
                ('chapters', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('student', 'Student'), ('senior', 'Senior')], default='basic', max_length=20)),
                ('membership_start', models.DateField(auto_now_add=True)),
                ('membership_expiry', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('max_items_allowed', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('checked_out', 'Checked Out'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('lost', 'Lost')], default='checked_out', max_length=20)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fine_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('library_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.libraryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checkout_date'],
            },
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['item_type'], name='core_librar_item_ty_147ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['is_available'], name='core_librar_is_avai_89913b_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['isbn'], name='core_librar_isbn_3a40c8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='core_transa_user_id_5b29f4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['library_item', 'status'], name='core_transa_library_68163a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['due_date'], name='core_transa_due_dat_1bc8b3_idx'),
        ),
    ]
