# Generated by Django 4.2.28 on 2026-02-28 09:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LibraryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("BOOK", "Book"), ("DVD", "DVD"), ("EBOOK", "E-Book")],
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("is_available", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "catalog_library_item",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "libraryitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalog.libraryitem",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                        ],
                        default="GOOD",
                        max_length=10,
                    ),
                ),
                (
                    "loan_period_days",
                    models.PositiveIntegerField(
                        default=14,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                ("author", models.CharField(db_index=True, max_length=255)),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=13, null=True, unique=True),
                ),
                (
                    "publication_year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1450),
                            django.core.validators.MaxValueValidator(2026),
                        ]
                    ),
                ),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "catalog_book",
            },
            bases=("catalog.libraryitem", models.Model),
        ),
        migrations.CreateModel(
            name="DVD",
            fields=[
                (
                    "libraryitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalog.libraryitem",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                        ],
                        default="GOOD",
                        max_length=10,
                    ),
                ),
                (
                    "loan_period_days",
                    models.PositiveIntegerField(
                        default=14,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                ("director", models.CharField(db_index=True, max_length=255)),
                ("runtime_minutes", models.PositiveIntegerField()),
                (
                    "release_year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1888),
                            django.core.validators.MaxValueValidator(2026),
                        ]
                    ),
                ),
                ("studio", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "catalog_dvd",
            },
            bases=("catalog.libraryitem", models.Model),
        ),
        migrations.CreateModel(
            name="EBook",
            fields=[
                (
                    "libraryitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalog.libraryitem",
                    ),
                ),
                ("file_size_mb", models.DecimalField(decimal_places=2, max_digits=8)),
                ("drm_protected", models.BooleanField(default=True)),
                ("download_url", models.URLField(blank=True)),
                ("author", models.CharField(db_index=True, max_length=255)),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=13, null=True, unique=True),
                ),
                (
                    "publication_year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1450),
                            django.core.validators.MaxValueValidator(2026),
                        ]
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("EPUB", "EPUB"),
                            ("MOBI", "MOBI"),
                            ("MP4", "MP4"),
                        ],
                        default="EPUB",
                        max_length=10,
                    ),
                ),
                ("total_licenses", models.PositiveIntegerField(default=1)),
                ("active_loans_count", models.PositiveIntegerField(default=0)),
                (
                    "access_duration_days",
                    models.PositiveIntegerField(
                        default=21,
                        help_text="How long a borrower can access the eBook after checkout.",
                    ),
                ),
            ],
            options={
                "db_table": "catalog_ebook",
            },
            bases=("catalog.libraryitem", models.Model),
        ),
    ]
